[tox]
isolated_build = true
envlist = py{310, 311, 312, 313, 314}, lint

[testenv]
deps =
    pytest
    coverage
commands =
    coverage run -m pytest --verbose
    coverage combine
    coverage report

[testenv:lint]
deps =
skip_install = true
allowlist_externals = poetry
commands =
    # use poetry to install all dev dependencies
    poetry install
    poetry run ruff check --fix
